apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-libgfgil
  janus-idp.io/tekton: go-libgfgil
  backstage.io/kubernetes-id: go-libgfgil
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-libgfgil
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
